---
apiVersion: v1
kind: ConfigMap

metadata:
  name: carros # sets in spring boot properties

data:
  application.yml: |-
    # MySQL
    spring:
      datasource:
        url: jdbc:mysql://spring-app-database-service:3306/database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: jonathan
        password: password
