apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externaldns
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/gbaeke/argo-demo.git
    targetRevision: HEAD
    path: charts/external-dns

    # helm specific config
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "cloudflare.apiToken"
        value: "atoken"

      # Release name override (defaults to application name)
      releaseName: external-dns

      valueFiles:
      - custom-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  # Sync policy
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).