# https://argoproj.github.io/argo-cd/user-guide/tool_detection/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  # By default, deleting an application will not perform a cascade delete, thereby deleting its resources. 
  # You must add the finalizer if you want this behaviour
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Jojoooo1/argocd-gitops.git
    targetRevision: master
    path: base/sealed-secert
  destination:
    server: https://kubernetes.default.svc
    namespace: default