---
apiVersion: v1
kind: ConfigMap

metadata:
  name: carros # sets in spring boot properties
  # namespace: set via kustomize

data:
  application.yml: |-
    
    # MySQL
    spring:
      datasource:
        url: jdbc:mysql://java-demo-database-service:3306/database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: jonathan
        password: password
