apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - rbac.yaml

  - database/service.yaml
  - database/deployment.yaml