---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  # annotations:
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: spring-app-backend-service
              servicePort: 8080
